# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseSocialMediaLogins' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'Firebase/Auth'
	pod 'Firebase/Core'

	#Google
	pod 'GoogleSignIn'

	  # Pods for Facebook
  	pod 'Bolts'
  	pod 'FBSDKCoreKit'
  	pod 'FBSDKLoginKit'

	# Twitter
	pod 'TwitterKit'

end
